-- Таблица сообщений
create table messages (
    id bigint generated by default as identity primary key,
    message_id bigint not null,
    chat_id bigint not null,
    user_id bigint not null,
    text text not null,
    timestamp timestamp with time zone not null,
    words text[] not null
);

-- Таблица слов и их контекста
create table words (
    id bigint generated by default as identity primary key,
    word text not null,
    message_id bigint not null,
    context text not null,
    created_at timestamp with time zone default now()
);

-- Индексы
create index idx_messages_chat_id on messages(chat_id);
create index idx_words_word on words(word);
create index idx_messages_timestamp on messages(timestamp); 